# Generated by Django 3.2.5 on 2021-07-08 00:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Existing_use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hamlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('identityNo', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('ocuppation', models.CharField(max_length=200)),
                ('household_type1', models.IntegerField()),
                ('household_type2', models.IntegerField()),
                ('household_type3', models.IntegerField()),
                ('household_type4', models.IntegerField()),
                ('parcentage_of_share', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Land Owner',
                'verbose_name_plural': 'Owner Details ',
            },
        ),
        migrations.CreateModel(
            name='OwnershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ownership_type', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pacel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('existing_use', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.existing_use')),
                ('hamlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.hamlet')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.institution')),
                ('owner', models.ManyToManyField(to='Data_Collection.Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposed_use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('council', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.council')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source_of_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('income_type', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Probate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person_with_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=200)),
                ('pacel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.pacel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pacel',
            name='proposed_use',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.proposed_use'),
        ),
        migrations.AddField(
            model_name='pacel',
            name='topology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.topology'),
        ),
        migrations.AddField(
            model_name='pacel',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.village'),
        ),
        migrations.AddField(
            model_name='owner',
            name='ownership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.ownershiptype'),
        ),
        migrations.CreateModel(
            name='Neighbour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neighbour_east', models.CharField(max_length=200)),
                ('neighbour_west', models.CharField(max_length=200)),
                ('neighbour_south', models.CharField(max_length=200)),
                ('neighbour_north', models.CharField(max_length=200)),
                ('pacel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.pacel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.institution_type'),
        ),
        migrations.AddField(
            model_name='hamlet',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.village'),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.region'),
        ),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_school', models.IntegerField()),
                ('froh_hospital', models.IntegerField()),
                ('from_water', models.IntegerField()),
                ('from_market', models.IntegerField()),
                ('pacel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.pacel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disputies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=2000)),
                ('pacel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.pacel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='council',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.district'),
        ),
    ]
