# Generated by Django 3.2.5 on 2021-08-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0002_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='household_type1',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='household_type2',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='household_type3',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='household_type4',
        ),
        migrations.AddField(
            model_name='distances',
            name='household_type1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distances',
            name='household_type2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distances',
            name='household_type3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distances',
            name='household_type4',
            field=models.IntegerField(null=True),
        ),
    ]
