# Generated by Django 3.2.5 on 2021-08-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0004_auto_20210801_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacel',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='pacel',
            name='owner',
        ),
        migrations.AddField(
            model_name='institution',
            name='pacel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.pacel'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data_Collection.pacel'),
        ),
    ]
