# Generated by Django 3.2.5 on 2021-08-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0005_auto_20210812_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='pacel',
        ),
    ]
