# Generated by Django 3.2.5 on 2021-08-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0006_rename_owner_owner_pacel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='zone',
            new_name='zone_id',
        ),
        migrations.AddField(
            model_name='district',
            name='zone_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
