# Generated by Django 3.2.5 on 2021-08-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0007_auto_20210812_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='council',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='council',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hamlet',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='village',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='village',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='updated_at',
        ),
    ]
