# Generated by Django 3.2.5 on 2021-08-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0008_auto_20210812_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='zone_id',
        ),
    ]
